# Change these first
owner: ivanbeltrame # Your GitHub organization or username, where this repository lives
repo: status-monitor-upptime # The name of this repository

sites:
  - name: ivanbeltrame.com
    url: https://www.ivanbeltrame.com
    
  - name: ivanweather.com
    url: https://www.ivanweather.com
    
  - name: Apps
    url: https://apps.ivanbeltrame.com
    
  - name: Games
    url: https://games.ivanbeltrame.com
    
  - name: Test page
    url: https://test.ivanbeltrame.com
    
  - name: Appunti
    url: https://appunti.ivanbeltrame.com
    
  - name: Belbab
    url: https://belbab.ivanbeltrame.com
    
  - name: CDN
    url: https://cdn.ivanbeltrame.com
    
  - name: Eleonora D'Arborea
    url: https://eleonoradarborea.ivanbeltrame.com
    
  - name: Er Galassia
    url: https://ergalassia.ivanbeltrame.com
    
  - name: Giulia Maggiore
    url: https://giuliamaggiore.ivanbeltrame.com
    
  - name: Misericordia
    url: https://misericordia.ivanbeltrame.com
    
  - name: Monumenti Aperti
    url: https://monumentiaperti.ivanbeltrame.com
    
  - name: Test Patente B
    url: https://patente.ivanbeltrame.com
    
  - name: Re di Roma
    url: https://rediroma.ivanbeltrame.com
    
  - name: I vandali in Sardegna
    url: https://vandalisardegna.ivanbeltrame.com
    
  - name: Doc ivanweather
    url: https://doc.ivanweather.ivanbeltrame.com
    
  - name: Links
    url: https://links.ivanbeltrame.com
    
  - name: TEST
    url: https://test-0001.ivanbeltrame.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ivanbeltrame.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.ivanbeltrame.com/img/icon.jpg
  name: Status monitor - Upptime
  introTitle: "**IvanBeltrame.com Real-Time Status Monitor**: Keep track of the live status and performance of ivanbeltrame.com with up-to-the-minute updates"
  introMessage: Stay updated with the real-time status and performance of ivanbeltrame.com. Our comprehensive dashboard provides up-to-the-minute information on uptime, downtime, and overall site health, ensuring you are always in the know.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/
    - title: Upptime
      href: https://github.com/upptime/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
